"""Ths solves problem #2 from Project Euler (https://projecteuler.net).

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By
starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""


def fibonacci_sum_even(fibonacci_limit=100):
    result = 0
    a, b = 1, 1
    while True:
        b, a = a, a + b
        if a > fibonacci_limit:
            break
        if a % 2 == 0:
            result += a
    return result


if __name__ == '__main__':
    print(fibonacci_sum_even(fibonacci_limit=4_000_000))

# last line of code
